[package]
name = "mm2-stdlib"
version = "0.1.0"
edition = "2024"

[dependencies]
eval-ffi = { git = "https://github.com/iCog-Labs-Dev/MORK", branch = "more-grounding-fns", package = "eval-ffi" }
eval = { git = "https://github.com/iCog-Labs-Dev/MORK", branch = "more-grounding-fns", package = "eval" }
mork-expr = { git = "https://github.com/iCog-Labs-Dev/MORK", branch = "more-grounding-fns", package = "mork-expr" }