[package]
name = "mm2-stdlib"
version = "0.1.0"
edition = "2024"

[dependencies]
eval-ffi = { git = "https://github.com/trueagi-io/MORK", package = "eval-ffi" }
eval = { git = "https://github.com/trueagi-io/MORK", package = "eval" }
mork-expr = { git = "https://github.com/trueagi-io/MORK", package = "expr" }